FROM armhf/alpine as builder

WORKDIR /root/
RUN apk add --update curl && \
    curl -sSLO https://dl.minio.io/server/minio/release/linux-arm/minio && \
    chmod 0755 ./minio

FROM scratch
COPY --from=builder /root/minio /usr/bin/minio

EXPOSE 9000
ENTRYPOINT ["minio"]
VOLUME ["/export"]
